# Generated by Django 4.2 on 2026-05-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OccasionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('theme_color', models.CharField(default='#ff69b4', max_length=7)),
                ('emojis', models.CharField(default='🎂🎈🎉', max_length=100)),
            ],
        ),
    ]
