# Generated by Django 4.2 on 2026-05-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField(default='Happy Birthday! 🎂')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
